### ISSUE TITLE
Is there an option to keep the original image file?

### ISSUE THREAD

**Issue by devhyunjae** [jtescher/carrierwave-imageoptimizer#12]
Thanks for the awesome rubygem!

I have a little question. I want to optimize the image and also want to keep the original image.

and i coded like this,

```ruby
class ImageUploader < CarrierWave::Uploader::Base
  process :optimize
  version :original
end
```

i was excepting two files

(optimized) uploaded_file.jpg
original_uploaded_file.jpg
but unfortunately, the original versioning is working with the image that already has been optimized :(

or is there an optimize option like this?

```ruby
  process optimize: [keep_original: true]
```

**Comment by elsurudo** [comment]
@devhyunjae Have you figured this out? I would also like to keep the original file.

**Comment by jtescher** [comment]
You can process versions just as you would run any other processing in carrierwave, so if you want to only process a different version move the `process :optimize` line into your version block. E.g.

```ruby
class ImageUploader < CarrierWave::Uploader::Base
  # Processing you want done on original here

  version :thumb do
    # Processing you want done on thumbnail here
    process :optimize
  end
end
```
