### ISSUE TITLE
Remvoe exif data from image

### ISSUE THREAD

**Issue by r00takaspin** [jtescher/carrierwave-imageoptimizer#16]
Hello, I am optimizing uploaded images for good rating at Google PageSpeed Insights Service. This service asks for remove of EXIF information from served images for better site performance.

Is it any opportunity to remove EXIF information from image using  gem carrierwave-imageoptimizer?

**Comment by jtescher** [comment]
What type of image are you trying to optimize? under the hood this will use [jpegoptim](https://github.com/tjko/jpegoptim) to optimize the files which will remove EXIF information.

**Comment by r00takaspin** [comment]
@jtescher yes, it is jpeg images. I see that jpegoptim has option to remove all headers from jpeg file via:
```
jpegoptim –strip-all someimage.jpg
``

it can be good, if gem had option that removes all headers from image.

I am preparing pull request for gem image_optimizer, that adds this option.

**Comment by jtescher** [comment]
So it looks like that is currently being passed in https://github.com/jtescher/image_optimizer/blob/master/lib/image_optimizer/jpeg_optimizer.rb#L7 are you not seeing that optimization applied?

**Comment by r00takaspin** [comment]
Ok, I see, thank you. Sorry for worrying.
