### ISSUE TITLE
What level of optimization should I expect?

### ISSUE THREAD

**Issue by lcpriest** [jtescher/carrierwave-imageoptimizer#17]
### JPEG
Conversion is 320*320 fill_to_pad

##### 1st image (initial size 1.4MB 3264 × 2448)
Old image: 151kb
Image with this gem: 148kb
Using imageoptim osx app on new image: 128kb

##### 2nd image (initial size 1.2MB 1600 × 1068)
Old image: 132kb
Image with this gem: 130kb
Using imageoptim osx app on new image: 122kb

##### Image (initial size 419kb 1800 × 530)
Old image: 15kb
New image: 15kb
Using imageoptim osx app on new image: 12kb

```
which optipng
/usr/local/bin/optipng
```

```
which jpegoptim
/usr/local/bin/jpegoptim
```

This is all with lossless compression, which I believe is the same as the client.

**Comment by jtescher** [comment]
This gem uses the `image_optimizer` gem so for jpeg it will apply https://github.com/jtescher/image_optimizer/blob/master/lib/image_optimizer/jpeg_optimizer.rb#L6-L11 and for png it will apply https://github.com/jtescher/image_optimizer/blob/master/lib/image_optimizer/png_optimizer.rb#L6-L10

That what you're looking for?

**Comment by lcpriest** [comment]
Exactly that.

Thank you!

**Comment by jtescher** [comment]
Great 👍
