### ISSUE TITLE
Running Nginx server

### ISSUE THREAD

**Issue by Rubioli** [jtescher/carrierwave-imageoptimizer#19]
I run my application on a Nginx and Passenger server. How can I install needed utilities?

Great Gem Thanks

**Comment by jtescher** [comment]
That depends on how you have provisioned your servers. You could have chef install jpegoptim and OptiPNG if you use that, or install it manually if you prefer. E.g. if you are running ubuntu you could run `apt-get install jpegoptim`

**Comment by Rubioli** [comment]
Great. Thanks for help . GREAT GEM :)
