### ISSUE TITLE
gif supporti,

### ISSUE THREAD

**Issue by optimum-dulopin** [jtescher/carrierwave-imageoptimizer#20]
Hi,

thanks for this very useful gem. And it would be even more wonderful if you could support gif with gifsicle for instance

**Comment by jtescher** [comment]
Sure, shouldn't be too difficult to add another optimizer to https://github.com/jtescher/image_optimizer/tree/master/lib/image_optimizer

If you wanted to submit a PR there I'd be happy to review it

**Comment by jtescher** [comment]
Fixed via https://github.com/jtescher/image_optimizer/pull/10
