### ISSUE TITLE
Bundler could not find compatible versions for gem "carrierwave"

### ISSUE THREAD

**Issue by leongg** [jtescher/carrierwave-imageoptimizer#21]
Hi! 
I'm trying to get the multi uploader function, and in my gemfile I added the line gem 'carrierwave', github: 'carrierwaveuploader/carrierwave' and when  I run bundle, I get this error from carrierwave-imageoptimizer
Bundler could not find compatible versions for gem "carrierwave":

```
Bundler could not find compatible versions for gem "carrierwave":
  In Gemfile:
    carrierwave

    carrierwave-imageoptimizer was resolved to 0.0.1, which depends on
      carrierwave (~> 0.8)

```

And the carrierwave source contains 'carrierwave' at: 1.0.0.beta ruby

What can I do to solve this? 

Thanks!

**Comment by jtescher** [comment]
Interesting. It looks like it is resolving to a very old version of this gem (0.0.1), could you try to add a version to your gemfile? something like `gem 'carrierwave-imageoptimizer', '~> 1.3'`

**Comment by grammakov** [comment]
Same error, specifying the version does not help.

**Comment by tomca32** [comment]
The problem is that carrierwave-imageoptimizer depends on
    carrierwave (~> 0.8)
while the current carrierwave version is: 1.0.0.rc

**Comment by mdesantis** [comment]
Same issue here trying to update Carrierwave to 1.0.0.rc

**Comment by mdesantis** [comment]
You have a pull request.
