### ISSUE TITLE
Skip png optimization

### ISSUE THREAD

**Issue by serodriguez68** [jtescher/carrierwave-imageoptimizer#24]
Hi!

1) Is there any way to **always** skip png optimization on a particular uploader (while leaving jpg optimization)?
I'm noticing that png optimization is a significant operation and that the benefit for my particular use case is just around 1%.

2) Is there any way to skip png optimization **conditionally** according to some property of the original file? (e.g file size?)

Thanks for your help!

**Comment by jtescher** [comment]
Hm looks like you can apply some conditional processing: https://github.com/carrierwaveuploader/carrierwave/wiki/how-to:-do-conditional-processing

You can skip PNG optimization globally by not including the pngoptim binary, but not sure if that's what you're looking for.

**Comment by duffyjp** [comment]
[image_optimizer](https://github.com/jtescher/image_optimizer) supports a configurable PNG optimization quality now.  Before it defaulted to "7" which was by my research (up to) 240 save iterations. 

Link to the addition:
https://github.com/jtescher/image_optimizer/pull/7/files

I'm in the same boat where my single core VPS takes several minutes to optimize a single PNG to save a few KB-- not really worth it.  Lowering the level to something basic would give you most of those KB but only take a few seconds.

**Comment by leemour** [comment]
@duffyjp Can you share the code you used to change png optimization level in an uploader?

**Comment by mitramejia** [comment]
@duffyjp can you please share how you changed the png optimization level?

**Comment by leemour** [comment]
@mitramejia `process optimize: [{ quiet: true, quality: 80, level: 1 }]` 
quality is for jpeg, level for png. level 1 was faster than 0 for me.

**Comment by duffyjp** [comment]
@mitramejia I ended up with `level: 3` which for my content was the best compromise between speed and filesize.


```ruby
  version :web do
    process :exif_orientation
    process :resize_to_safari
    process :colorspace
    process :optimize => [{ quality: 75, level: 3, quiet: true }]
  end
```

**Comment by jtescher** [comment]
Closing for now
