### ISSUE TITLE
Carrierwave 2.x support

### ISSUE THREAD

**Issue by vadim-zverugo** [jtescher/carrierwave-imageoptimizer#31]
Carrierwave 2.0.0 is released https://github.com/carrierwaveuploader/carrierwave but imageoptimizer requires >= 0.8, < 2.0

```
Bundler could not find compatible versions for gem "carrierwave":
  In Gemfile:
    carrierwave (~> 2.0.0)

    carrierwave-imageoptimizer (~> 1.4.0) was resolved to 1.4.0, which depends on
      carrierwave (>= 0.8, < 2.0)
```

**Comment by jtescher** [comment]
Latest release should support his now thanks to @tab 

https://rubygems.org/gems/carrierwave-imageoptimizer/versions/1.4.1
