### ISSUE TITLE
jpeg optim not installed on heroku production server

### ISSUE THREAD

**Issue by jhorsch** [jtescher/carrierwave-imageoptimizer#9]
Hi,

Thanks for this gem.  I was working great in development becuasee I had ran ...

brew install jpegotpim

However when running in production, my heroku log reads

2015-01-06T06:59:31.954359+00:00 app[web.1]: Attempting to optimize a jpeg without jpegoptim installed. Skipping...

Wouldn't the gem install jpegoptim, or do I have to install something on the heroku server as well?

Thanks

**Comment by czj** [comment]
Hello,

Heroku recommends using a buildpack to get jpegoptim working:
https://github.com/jayzes/heroku-buildpack-jpegoptim

You could also add jpegoptim to your app's bin/ directory, but that's not a clean way to do it (for me).

**Comment by jtescher** [comment]
@czj is correct. You need to have the jpegoptim binary installed on your server and the buildpack is the recommended way. If you install via another method you can always set the path via the `JPEGOPTIM_BIN` env var.

**Comment by jhorsch** [comment]
When I create the buildpacks file

Do I name it   filename.buildpacks

or just 

.buildpacks  ( like a .env file)

https://github.com/jayzes/heroku-buildpack-jpegoptim
https://github.com/heroku/heroku-buildpack-ruby

**Comment by jtescher** [comment]
Just `.buildpacks` with the contents explained in https://github.com/jayzes/heroku-buildpack-jpegoptim#usage

**Comment by jhorsch** [comment]
Thanks, that was my guess as well.  

I created a file named .buildpacks and added this
    https://github.com/jayzes/heroku-buildpack-jpegoptim
    https://github.com/heroku/heroku-buildpack-ruby

Then ran
    heroku create --buildpack https://github.com/ddollar/heroku-buildpack-multi

But when I run
    heroku run "jpegoptim -V"

I see
   bash: jpegoptim: command not found


What am I missing?

Thanks

**Comment by FanaHOVA** [comment]
@jhorsch You need to push the buildpack with "git push heroku master", you should then see the jpegoptim installation going on and then it should finally work!
